/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rshape;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileFilter;
import java.util.Enumeration;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableColumnModelListener;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import rshape.io.StructReader;

/**
 *
 * @author easimer
 */
public class RShapeGUI extends javax.swing.JFrame {

    private javax.swing.JTextArea landscape;
    private javax.swing.JTextArea data1;
    private javax.swing.JTextArea data2;
    private javax.swing.JTextArea roads;
    private javax.swing.JTextArea entities;
    
    private Map map;
    
    /**
     * Creates new form RShapeGUI
     */
    public RShapeGUI() {
        initComponents();
        
        landscape = new JTextArea();
        data1 = new JTextArea();
        data2 = new JTextArea();
        roads = new JTextArea();
        entities = new JTextArea();
        
        jTabbedPane1.addTab("Landscape", landscape);
        jTabbedPane1.addTab("Data 1", data1);
        jTabbedPane1.addTab("Data 2", data2);
        jTabbedPane1.addTab("Roads", roads);
        jTabbedPane1.addTab("Entities", entities);
        JMenuItem newFile = new JMenuItem();
        newFile.setText("New");
        newFile.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_DOWN_MASK));
        newFile.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                map = new Map(32, 32);
            }
        });
        JMenuItem saveFile = new JMenuItem();
        saveFile.setText("Save");
        saveFile.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK));
        saveFile.addActionListener(new SaveFile());
        JMenuItem openFile = new JMenuItem();
        openFile.setText("Load");
        openFile.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_DOWN_MASK));
        openFile.addActionListener(new OpenFile());
        jMenu1.add(newFile);
        jMenu1.add(openFile);
        jMenu1.add(saveFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void Show() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RShapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RShapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RShapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RShapeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setVisible(true);
    }
    
    class SaveFile implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ae)
        {
            JFileChooser fc = new JFileChooser();
            int ret = fc.showSaveDialog(fc);
            switch(ret)
            {
                case JFileChooser.APPROVE_OPTION:
                    
                    break;
                case JFileChooser.CANCEL_OPTION:
                    break;
            }
        }
    }
    
    class OpenFile implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ae)
        {
            JFileChooser fc = new JFileChooser();
            int ret = fc.showOpenDialog(fc);
            switch(ret)
            {
                case JFileChooser.APPROVE_OPTION:
                    int lofp = fc.getSelectedFile().getName().lastIndexOf('.');
                    if(lofp >= 0)
                    {
                        switch(fc.getSelectedFile().getName().substring(lofp + 1))
                        {
                            case "rsf":
                                map = RShape.LoadRShaperFile(fc.getSelectedFile());
                                break;
                            case "map":
                                map = RShape.Decompile(fc.getSelectedFile().getName());
                                break;
                                
                        }
                    }
                    landscape.setText(map.layers[0]);
                    data1.setText(map.layers[1]);
                    data2.setText(map.layers[2]);
                    roads.setText(map.layers[3]);
                    entities.setText(map.layers[4]);
                    break;
                case JFileChooser.CANCEL_OPTION:
                    break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}